# Generated by Django 5.0.6 on 2024-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('licenceapp', '0002_alter_licence_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='licences',
            field=models.ManyToManyField(blank=True, to='licenceapp.licence'),
        ),
    ]
