# Generated by Django 5.0.6 on 2024-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_licences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='licences',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='typeCompte',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STANDARD', max_length=10),
        ),
    ]
