# Generated by Django 5.0.6 on 2024-06-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_licences_alter_customuser_is_admin_and_more'),
        ('licenceapp', '0005_alter_licence_user_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='licences',
            field=models.ManyToManyField(blank=True, related_name='users', to='licenceapp.licence'),
        ),
    ]
