version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    ports:
      - 5000:5000

  djangowim:
    container_name: django_wim_app
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - ./:/app/
    ports:
      - 8081:8081
    environment:
      - DEBUG=1
      - SECRET_KEY=0930j30h302hj320
      - ALLOWED_HOSTS=localhost,127.0.0.1,webinaire.friare.org
    depends_on:
      - redis

