# Generated by Django 5.0.6 on 2024-06-21 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('centre_formation', 'Centre de Formation'), ('personnel', 'Personnel'), ('Autre', 'Autre')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exp', models.DateField()),
                ('valeur', models.CharField(default='c75ab16883124dcd8203f8e4741a7d7e', editable=False, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(related_name='licences', to='licenceapp.classe')),
                ('niveaux', models.ManyToManyField(related_name='licences', to='licenceapp.niveau')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='licenceapp.source')),
            ],
        ),
    ]
