# Generated by Django 5.0.6 on 2024-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='0100d0b4b0214f24b6479a18ffc39f12', editable=False, max_length=32, unique=True),
        ),
    ]
