# Generated by Django 5.0.6 on 2024-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='6c99ad4dbe4143419255ed280c94b457', editable=False, max_length=32, unique=True),
        ),
    ]
