# Generated by Django 5.0.6 on 2024-06-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0002_alter_licence_valeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='niveaux',
        ),
        migrations.AddField(
            model_name='licence',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='licenceapp.classe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licence',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='licenceapp.niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licence',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='28770f493ed74881bd49376268580116', editable=False, max_length=32, unique=True),
        ),
    ]
