# Generated by Django 5.0.6 on 2024-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0005_alter_licence_user_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='1582e45d878741eda3cf3f12a30a4220', editable=False, max_length=32, unique=True),
        ),
    ]
