# Generated by Django 5.0.6 on 2024-06-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0006_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='licenceapp.classe'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='licenceapp.niveau'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='485e937ee84a4874b3dbc592b39290c7', editable=False, max_length=32, unique=True),
        ),
    ]
