# Generated by Django 5.0.6 on 2024-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0007_alter_licence_classe_alter_licence_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='4406188090e746d484d1124b5fc007b3', editable=False, max_length=32, unique=True),
        ),
    ]
