# Generated by Django 5.0.6 on 2024-06-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0008_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='30bd7d4cf4f140c38af8a037bd5a0915', editable=False, max_length=32, unique=True),
        ),
    ]
