# Generated by Django 5.0.6 on 2024-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0010_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='059e8924d9ad4a48862d576ed988125f', editable=False, max_length=32, unique=True),
        ),
    ]
