# Generated by Django 5.0.6 on 2024-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0011_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='0ecf234707304d0fbca3c3b592dfcf69', editable=False, max_length=32, unique=True),
        ),
    ]
