# Generated by Django 5.0.6 on 2024-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenceapp', '0012_alter_licence_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='valeur',
            field=models.CharField(default='a82a42a1b6ec494788acf1d4a65467b6', editable=False, max_length=32, unique=True),
        ),
    ]
