# Generated by Django 4.2.13 on 2024-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenceapp', '0001_initial'),
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='licences',
            field=models.ManyToManyField(blank=True, related_name='users', to='licenceapp.licence'),
        ),
    ]
