# Generated by Django 4.2.13 on 2024-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
