# Generated by Django 5.0.6 on 2024-06-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='background_music',
        ),
    ]
