# Generated by Django 5.0.6 on 2024-06-18 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenceapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatmaker', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duree_enreg', models.IntegerField(help_text='Duration in seconds')),
                ('ecoutes', models.IntegerField(default=0)),
                ('enreg_ID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interprete', models.CharField(max_length=255)),
                ('isFree', models.BooleanField(default=True)),
                ('lyrics_enreg', models.TextField(blank=True, null=True)),
                ('style_enreg', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('url_enreg', models.URLField()),
                ('url_img', models.URLField(blank=True, null=True)),
                ('url_mp3', models.URLField()),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenceapp.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='musicapp.music')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenceapp.classe')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenceapp.matiere')),
                ('musics', models.ManyToManyField(related_name='playlists', to='musicapp.music')),
            ],
        ),
    ]
