# Generated by Django 5.0.6 on 2024-06-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favori',
            name='music',
        ),
        migrations.AddField(
            model_name='favori',
            name='musics',
            field=models.ManyToManyField(related_name='favoris', to='musicapp.music'),
        ),
    ]
