# Generated by Django 5.0.6 on 2024-06-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_favori_music_favori_musics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='enreg_ID',
        ),
    ]
