# Generated by Django 5.0.6 on 2024-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_remove_music_enreg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file_enreg',
            field=models.FileField(blank=True, null=True, upload_to='enreg/'),
        ),
        migrations.AddField(
            model_name='music',
            name='file_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='music',
            name='file_mp3',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
    ]
